tweet/Post/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet
from . import views

router = DefaultRouter()

router.register(r'', PostViewSet, basename='posts')


app_name = 'post'

urlpatterns = [
    path('api/', include(router.urls)),
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('new/', views.post_new, name='post_new'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<pk>/remove/', views.post_remove, name='post_remove'),
    path('like/', views.like_post, name='like_post'),
    path('liked/', views.liked_posts, name='liked_posts'),
]

tweet/User/urls.py
from django.urls import path, include
from .views import UserViewSet, register
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

# router.register(r'', UserViewSet, basename='user')

app_name = 'users'

urlpatterns = [
    # path('api/', include(router.urls)),
    path('', UserViewSet.list, name='user_list'),
    path('<int:pk>/', UserViewSet.get_queryset, name='user_detail'),
    path('new/', UserViewSet.create, name='user_new'),
    path('<int:pk>/edit/', UserViewSet.update, name='user_edit'),
    path('<pk>/remove/', UserViewSet.destroy, name='user_remove'),
    path('register/', register, name='register'),
]

tweet/tweet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user/', include('User.urls')),
    path('post/', include('Post.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

tweet/Post/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
User = get_user_model()


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, unique=True)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    like_count = models.ManyToManyField(User, related_name="post_likes", blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post:post_detail', kwargs={'pk': self.id})

    def total_likes(self):
        return self.like_count.count()

tweet/User/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):

    def __str__(self):
        return self.username

tweet/Post/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

tweet/User/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter Password Here...'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password...'}))

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError("Password Mismatch")
        return confirm_password

tweet/Post/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404
from rest_framework import permissions
from rest_framework.viewsets import ModelViewSet

from .forms import PostForm
from .models import Post
from .serializers import PostSerializer


class PostViewSet(ModelViewSet):
    permission_classes = [permissions.IsAuthenticated]
    queryset = Post.objects.all().order_by('-created_date')
    serializer_class = PostSerializer


def post_list(request):
    posts = Post.objects.all().order_by('-created_date')
    return render(request, 'post/post_list.html', {'posts': posts})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    is_liked = False
    if post.like_count.filter(id=request.user.id).exists():
        is_liked = True
    return render(
        request,
        'post/post_detail.html',
        {
            'post': post,
            'is_liked': is_liked,
            'total_likes': post.total_likes,
        }
    )


@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post:post_detail', pk=post.pk)
    else:
        form = PostForm()

    return render(request, 'post/post_edit.html', {'form': form})


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'post/post_edit.html', {'form': form})


@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('post:post_list')


def like_post(request):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    is_liked = False
    if post.like_count.filter(id=request.user.id).exists():
        post.like_count.remove(request.user.id)
        is_liked = False
    else:
        post.like_count.add(request.user.id)
        is_liked = True
    return HttpResponseRedirect(post.get_absolute_url())


def liked_posts(request):
    posts = request.user.post_likes.all()
    return render(request, 'post/liked_post_list.html', {'liked_posts': posts})

tweet/User/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from rest_framework import permissions
# Create your views here.
from rest_framework.viewsets import ModelViewSet

from .forms import UserRegistrationForm
# from rest_framework.permissions import BasePermission
from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(ModelViewSet):
    permission_classes = [permissions.IsAuthenticated]
    serializer_class = UserSerializer

    def get_queryset(self):
        queryset = User.objects.filter(id=self.request.user.id)
        return queryset


def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            return redirect('post:post_list')
    else:
        form = UserRegistrationForm()
        context = {
            'form': form,
        }
        return render(request, 'registration/register.html', context)

tweet/templates/home.html
{% extends 'post/base.html' %}

{% block content %}
<div class="home">

    <h1>          WELCOME          </h1>

</div>

{% endblock %}

tweet/templates/post/base.html
{% load static %}

<html >
    <head>
        <title>Ishu's Tweets</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    </head>
    <body> 
        <div class="navbar navbar-expand-sm bg-dark navbar-dark">
            <div class="container-fluid">    
                <h1><a class="name" href="{% url 'post:post_list' %}">Ishu's Tweets</a></h1>
                <div class="navbar-right row">
                    {% if user.is_authenticated %}
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" style="margin-top: 7.5px" href="{% url 'post:post_new' %}" class="top-menu"><span class="fa fa-plus" aria-hidden="true"> New Post </span></a>
                            </li>
                            <li class="nav-item">
                                <p style="font-size: 20px" class="top-menu nav-link">Hello {{ user.username }} (<a href="{% url 'logout' %}"><span class="fa fa-sign-out" aria-hidden="true"></span>&nbsp; log out</a>)</p>
                            </li>
                        </ul>
                        <a class="nav-link" style="margin-top: 7.5px" href="{% url 'post:liked_posts' %}" class="top-menu"><span aria-hidden="true"> Liked Posts </span></a>
                    {% else %}
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'login' %}" class="top-menu"><span class="fa fa-lock" aria-hidden="true"> Login </span></a>
                            </li>
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="content container">
            <div class="row justify-content-center">
                <div class="col-md-8 after-navbar">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

tweet/templates/post/liked_post_list.html
{% extends 'post/base.html' %}

{% block content %}
    {% for post in liked_posts %}
        <div class="post">
            
            <h2><a href="{% url 'post:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <div class="date">
                <p>published: {{ post.created_date }}</p>
                <small>{{ linebreaksbr }}</small>
            </div>
        </div>
    {% endfor %}
{% endblock %}

tweet/templates/post/post_detail.html
{% extends 'post/base.html' %}

{% block content %}
<div class="post">

    {% if user.pk == post.author.pk %}
    <a class="btn btn-primary" href="{% url 'post:post_edit' pk=post.pk %}"><span class="fa fa-pencil"></span></a>
    <a class="btn btn-primary" href="{% url 'post:post_remove' pk=post.pk %}"><span class="fa fa-remove"></span></a>
    {% endif %}

    <h2>{{ post.title }}</h2>

    <p>{{ post.text|linebreaksbr }}</p>

    {% if request.user.is_authenticated %}
    <form action="{% url 'post:like_post' %}" method="post">
        {% csrf_token %}
        {% if is_liked %}
        <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-primary">Dislike</button>
        {% else %}
        <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-primary">Like</button>
        {% endif %}
    </form>
    {% endif %}

    {{ total_likes }} Like{{ total_likes|pluralize }}

</div>

{% endblock %}

tweet/templates/post/post_edit.html
{% extends 'post/base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

tweet/templates/post/post_list.html
{% extends 'post/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            
            <h2><a href="{% url 'post:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <div class="date">
                <p>published: {{ post.created_date }}</p>
                <small>{{ linebreaksbr }}</small>
            </div>
        </div>
    {% endfor %}
{% endblock %}